#!/usr/bin/env bash

# emulate debian a2ensite/a2dissite commands
# https://serverfault.com/questions/548212/how-to-a2ensite-and-a2dissite

SITES_AVAILABLE="/etc/httpd/sites-available";
SITES_ENABLED="/etc/httpd/sites-enabled";

if [ $1 ]; then
  if [ ! -f "${SITES_ENABLED}/${1}" ]; then
    echo "Site ${1} was already disabled!";
  elif [ ! -w $SITES_ENABLED ]; then
    echo "You don't have permission to do this. Try to run the command as root."
  elif [ -f "${SITES_AVAILABLE}/${1}" ]; then
    echo "Disabling site ${1}...";
    unlink $SITES_ENABLED/$1
    echo "done!"
  else
    echo "Site not found!"
  fi
else
  echo "Please, inform the name of the site to be enabled."
fi
